
var talks = {
  "t1" : {
    "title" : "Desarrollo con Guice, Jersey y AppEngine",
    "description" : "Para el desarrollo de aplicaciones basadas en Java, el camino trillado siempre ha sido el basado en stacks típicos (Spring, JEE, SQL) que vienen a ser el equivalente de LAMP para el mundo Java. Durante esta charla se contrastará este modelo con un caso real basado en Guice para la inyección de dependencias, Jersey para el interfaz REST y AppEngine como servidor de aplicaciones en la nube.",
    "level": "Advanced",   // Advanced || Intermediate || Beginner
    "tech": ["GTUG","JAVA", "ORACLE"] ,  
    "hash" : "t1",  // locate it in talks page
    "lang": "ES",
    "speaker" : {
      "name" : "Nacho Coloma",
      "mail" : "icoloma@extrema-sistemas.com",
      "twitter" : "@nachocoloma",
      "blog" : "icoloma.blogspot.com",
      "img": "nachocoloma.jpg"
    },
    "slides" :"http://www.slideshare.net/icoloma/codemotion-appengine",
    "code" :"http://github.com/icoloma",
    "related_videos" : [
      "http://www.youtube.com/watch?v=if6EMTVZ200", 
      "http://www.youtube.com/watch?v=IXXZEhjA5IY&feature=g-all-u"
    ],
    "related_posts": [
      "http://icoloma.blogspot.com.es/2011/05/firefox-4-and-36-at-same-time.html",
      "http://icoloma.blogspot.com.es/2010/04/our-web-development-in-2010-slides-are.html"]
  },

  "t2" : {
    "title" : "Multi-threaded Performance and Scalability",
    "description" : "Twelve years ago, Intel predicted we would have 10 GHz chips by now. However, instead of becoming faster, our chips are becoming slower in order to cope with all the heat generated by our many cores. The largest supercomputer, \"K\" in Japan, currently has over half a million cores, running at 2GHz each. This gives us an incredible amount of processing power, but contention can also become a huge drain on performance. In this talk, we will look at some tips on how to think about performance in the multi-threaded world. We will compare latency and throughput and show now Little's and Amdahl's laws influence our ability to scale up our systems.",
    "level": "Advanced",   // Advanced || Intermediate || Beginner
    "tech": ["JAVA"] ,  
    "hash" : "t2",  // locate it in talks page
    "lang": "EN",
    "speaker" : {
      "name" : "Dr. Heinz Kabutz",
      //"mail" : "",
      "twitter" : "@heinzkabutz",
      "blog" : "http://www.javaspecialists.eu",
      "img": "hkabutz.jpg"
    },
    /*
    "slides" :"",
    "code" :"",
    "related_videos" : [],
    "related_posts": []
    */
  },
  

}

var tracks = 7;

var schedule = [
  { title: "time",        talks : ["track1","track2","track3","track4","track5", "track6", "track7"]}
 ,{ title: "08:00-09:00", talks : ["register"]}
 ,{ title: "09:00-09:30", talks : ["welcome"]}
 ,{ title: "09:30-10:15", talks : [ talks.t1, talks.t2, talks.t1, talks.t1, talks.t1, talks.t1, talks.t1 ]}
 ,{ title: "10:30-11:15", talks : [ talks.t1, talks.t1, talks.t1, talks.t1, talks.t1, talks.t1, talks.t1 ]}
 ,{ title: "11:15-11:45", talks : ["coffeBreak"]}
 ,{ title: "11:45-12:30", talks : [ talks.t1, talks.t1, talks.t1, talks.t1, talks.t1, talks.t1, talks.t1 ]}
 ,{ title: "12:45-13:30", talks : [ talks.t1, talks.t1, talks.t1, talks.t1, talks.t1, talks.t1, talks.t1 ]}
 ,{ title: "13:30-15:00", talks : ["lunch"]}
 ,{ title: "15:00-15:45", talks : [ talks.t1, talks.t1, talks.t1, talks.t1, talks.t1, talks.t1, talks.t1 ]}
 ,{ title: "16:00-16:45", talks : [ talks.t1, talks.t1, talks.t1, talks.t1, talks.t1, talks.t1, talks.t1 ]}
 ,{ title: "16:45-17:15", talks : ["coffeBreak"]}
 ,{ title: "17:15-18:00", talks : [ talks.t1, talks.t1, talks.t1, talks.t1, talks.t1, talks.t1, talks.t1 ]}
 ,{ title: "18:15-19:00", talks : [ talks.t1, talks.t1, talks.t1, talks.t1, talks.t1, talks.t1, talks.t1 ]}
 ,{ title: "19:00-19:15", talks : ["closing"]}
];

var workshops = [
  { title: "time",        talks : ["workshop"]}
 ,{ title: "08:00-09:00", talks : [talks.t1]}
 ,{ title: "15:00-15:45", talks : [talks.t2]}
];


module.exports = {
  talks : talks,
  tracks: tracks,
  schedule : schedule,
  workshops : workshops
}
